sudo: required
language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.npm
    - node_modules
  npm: true
  yarn: true
notifications:
  email: false
services:
  - docker
addons:
  chrome: stable
  sonarcloud:
    organization: seantrane-github
git:
  depth: false
branches:
  only:
    - master
    - /^release.*$/
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - PATH=$PWD:$PATH
before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g github-label-sync stshell typescript @angular/cli
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - travis_retry npm install
stages:
  - test
  - name: deploy
    if: repo = seantrane/mean-stacker
        AND type != pull_request
        AND branch = master
jobs:
  include:
    - stage: test
      name: 'Checks and Tests'
      script:
        - '[[ $TRAVIS_BRANCH =~ ^release.*$ ]] && npm audit || echo "Skipping npm audit";'
        - commitlint-travis
        - travis_retry github-label-sync -a "$GH_TOKEN" -l 'https://git.io/fAe5i' seantrane/mean-stacker
        - npm run lint
        - docker pull koalaman/shellcheck:stable
        - docker run -v "$PWD:/mnt" koalaman/shellcheck ./run ./*.sh || travis_terminate 1;
        # - xvfb-run npm run test
        # - xvfb-run npm run e2e -- --no-progress
        - sonar-scanner
    - stage: deploy
      name: 'Publish, Upload and Deploy'
      script:
        - npm run semantic-release
