sudo: required
language: node_js
services:
  - docker
addons:
  sonarcloud:
    organization: "seantrane-github"
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - node_modules
  npm: true
  yarn: true
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper.*$/
before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g github-label-sync greenkeeper-lockfile stshell @angular/cli karma-cli protractor semantic-release typescript webpack webpack-dev-server
install:
  - travis_retry ./run --install
stages:
  - prepare cache
  - test
  - integration
  - name: deploy
    if: repo = seantrane/mean-stacker
        AND type != pull_request
        AND branch = master
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test
      name: 'Greenkeeper lockfile update'
      if: branch =~ /^greenkeeper.*$/
      script:
        - greenkeeper-lockfile-update
    - stage: test
      name: 'Lint Checks and Chores'
      script:
        - commitlint-travis
        - ./run --lint
        - travis_retry github-label-sync -a "$GH_TOKEN" -l 'https://git.io/fAe5i' seantrane/mean-stacker
    - stage: test
      name: 'Unit Testing on master branch and PRs'
      if: branch = master
      script:
        # disabled until fixed:
        # - ./run --debug --test --report
        # - ./run --debug --e2e
        - sonar-scanner
    - stage: test
      name: 'Unit Testing on other branches'
      if: branch != master
      script: true
        # disabled until fixed:
        # - ./run --debug --test
        # - ./run --debug --e2e
    - stage: integration
      name: 'Greenkeeper lockfile upload'
      if: branch =~ /^greenkeeper.*$/
      script:
        - greenkeeper-lockfile-upload
    - stage: deploy
      name: 'Publish, Upload and Deploy'
      script: ./run --debug --publish
